//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorityLevel
    {
        public int A_Id { get; set; }
        public string AuthorityName { get; set; }
        public int AccessLevel { get; set; }
    }
}
