//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoDiscountValue
    {
        public int PromoDiscountValueID { get; set; }
        public byte DiscountValueType_DiscountValueTypeId { get; set; }
        public int Promos_PromoId { get; set; }
        public Nullable<int> PromoId { get; set; }
        public Nullable<int> DiscountValueType { get; set; }
        public Nullable<double> Discountvalue { get; set; }
    }
}
